apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: automl-web
  name: automl-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: automl-web
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: automl-web
    spec:
      containers:
        - image: automl/automl:v1beta1 # change yourself image
          name: automl-web
          imagePullPolicy: Never # load image from local
          ports:
            - containerPort: 8081
          resources: { }
      restartPolicy: Always
status: { }
