server:
    port: 8081
    path:
        globalPrefix: /v1beta1

spring:
    datasource:
        primary:
            jdbc-url: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/automl?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
    mail:
        default-encoding: UTF-8
        protocol: smtp
        host: smtp.163.com
        port: 465
        username: #配置发送邮件
        password: #配置发送邮件秘钥
        properties:
            mail:
                smtp:
                    auth: true
                    ssl:
                        enable: true

#mybatis:
#
#  type-aliases-package: com.automl.api.entity
#  configuration:
#    map-underscore-to-camel-case: true

mybatis-plus:
    mapper-locations: classpath:mapper/automl/*.xml
